version: '3'
services:
  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - .:/app
    ports:
      - "8888:80"
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: ./docker/php-fpm
    volumes:
      - .:/app
    depends_on:
      - mysql

  php-cli:
    build:
      context: ./docker/php-cli
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - .:/app
      - composer:/home/app/cache/composer

  mysql:
    platform: linux/x86_64
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: testapp
      MYSQL_USER: app_user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql/entrypoint-scripts:/docker-entrypoint-initdb.d
    ports:
      - "33066:3306"
    command:
      - "--innodb-use-native-aio=0"
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      interval: 5s
      timeout: 20s
      retries: 10

  composer:
    restart: 'no'
    image: composer/composer
    volumes:
      - .:/app
volumes:
  composer:
  mysql-data:

